### ISSUE TITLE
Method status code FAIL when trying to --revertnoerase on Crucial MX100

### ISSUE THREAD

**Issue by Cysioland** [r0m30/msed#31]
I tried to completely remove admin password via --revertnoerase, but when I tried to do this, it replied with "Method status code FAIL". I was able to disable locking range, so I can access that disk no problem, I just can't revert it to unprotected state.

**Comment by r0m30** [comment]
Can you try a revertnoerase with a trace -vvvvv  as the first parameter.  I'm not sure with the info you have given me so far but it looks like the the drive firmware detected an internal error when it tried to revert the drive.  That is almost certainly a firmware bug but let's see what the trace tells us.

**Comment by Cysioland** [comment]
@r0m30  https://gist.github.com/Cysioland/89bbab19d6ace7b7911c

**Comment by r0m30** [comment]
There is nothing unusual in the message flow up to the failure. This is almost certainly a firmware bug.  The spec defines the FAIL return code as "This status is returned when a method fails in a manner for which none of the other failure statuses apply."
aka I'm so confused......

If you're willing to try it we could set up a raw command that changes the length of the parameter number but that is a long shot.  Samsung and Seagate aren't picky about the length but the Crucial M500 will only accept a length of 3.

The other possibility is to try and report a bug to Crucial but since their primary audience is MS eDrive I'm not sure how responsive they would be.

**Comment by Cysioland** [comment]
@r0m30 Is there any risk to lose my data or, even worse, to brick the whole disk? Data is not a big problem, as I can image, but bricking that kinda expensive disk is no fun ;__;

**Comment by r0m30** [comment]
Given that the disk is confused just about anything is possible.  I can't say for sure that it is safe for either the data or the functionality of the drive.

**Comment by Cysioland** [comment]
@r0m30 Would you explain that part about command parameter length and all?

**Comment by r0m30** [comment]
The TCG messages are tokenized, the first part of the token is a descriptor of the data type and length.  The revertnoerase function is implemented as the keepglobalrangekey sub-parameter of the revertsp command.  The sub-parameter number is 0x060000 (3 bytes) but some drives accept the parameter number as 0x00060000 (4 bytes).  

A few other things I found while looking at this, from the spec:
"The following condition SHALL guarantee that the TPer can comply with the request to keep the Global Range’s media encryption key:
o The Global Range is either Read Unlocked or Write Unlocked at the time of invocation of RevertSP
If the TPer cannot comply with the request to keep the Global Range’s media encryption key, then the method invocation SHALL fail with status FAIL, and the SP SHALL NOT change life cycle states.
If the Locking SP was created in manufacturing, support for the KeepGlobalRangeKey parameter is mandatory for the Locking SP.

**Comment by r0m30** [comment]
Sorry that wasn't finished......

Is it possible that you tried to run the revertnoerase while the drive was locked?

**Comment by Cysioland** [comment]
I tried it from rescue USB, when I was locked out because of bug with PBA,
and same message. Then I disabled locking, and tried the same command from
my regular operating system, and still fails.

**Comment by Cysioland** [comment]
@r0m30 And, from what you wrote, I think I may go with it after imaging my disk, because I think the worst thing to happen will be likely the need of PSID revert.

**Comment by r0m30** [comment]
If you decide to give it a try let me know and I'll figure out the command and test it.

**Comment by Cysioland** [comment]
I might give it a try

**Comment by Cysioland** [comment]
@r0m30 Any progress about figuring out a command?

**Comment by r0m30** [comment]
You said you might try it, so I was waiting for you to decide.

________
Mike

**Comment by Cysioland** [comment]
So let's go with it, worst case scenario will be data loss, so with full
disk image I'd be safe.

**Comment by r0m30** [comment]
OK, so you need to follow the directions for removing OPAL substituting this command for the revertnoerase.

msed --rawCmd 3 0000000900010001 <password> 0000000000000001 0000000600000011 f0f2840006000001f3f1  \\.\PhysicalDrive?

Substitute your password and use the correct physical drive identifier.
You will get  error messages about EndSession failing, this is normal because the drive terminates the session immediately and msed handles this when you run the regular command.
 
I've tested it on a ST500LT025 and it worked, but so does the three byte parameter number version.
here is a console log of my test.
PS U:\Users\r0m30\Documents\Visual Studio 2015\Projects> dir e:


    Directory: e:\


Mode                LastWriteTime     Length Name
----                -------------     ------ ----
-a---         8/23/2015   2:15 PM          0 THis should still be here after im done.txt


PS U:\Users\r0m30\Documents\Visual Studio 2015\Projects> msed --query \\.\PhysicalDrive1

\\.\PhysicalDrive1 ATA ST500LT025-1DH142                        0001SDM7             W3P34NH9
TPer function (0x0001)
    ACKNAK = N, ASYNC = N. BufferManagement = N, comIDManagement  = N, Streaming = Y, SYNC = Y
Locking function (0x0002)
    Locked = N, LockingEnabled = N, LockingSupported = Y, MBRDone = N, MBREnabled = N, MediaEncrypt = Y
Geometry function (0x0003)
    Align = Y, Alignment Granularity = 8 (4096), Logical Block size = 512, Lowest Aligned LBA = 0
SingleUser function (0x0201)
    ALL = N, ANY = N, Policy = Y, Locking Objects = 16
DataStore function (0x0202)
    Max Tables = 16, Max Size Tables = 52428800, Table size alignment = 4096
OPAL 2.0 function (0x0203)
    Base comID = 0x07fe, Initial PIN = 0x0 , Reverted PIN = 0x0 , comIDs = 2
    Locking Admins = 4, Locking Users = 16, Range Crossing = N

TPer Properties:
  MaxMethods = 1  MaxSubpackets = 1
  MaxPacketSize = 17388  MaxPackets = 1  MaxComPacketSize = 17408
  MaxResponseComPacketSize = 17408  MaxSessions = 1  MaxIndTokenSize = 17352
  MaxAuthentications = 24  MaxTransactionLimit = 1  DefSessionTimeout = 0
  MaxSessionTimeout = 0  MinSessionTimeout = 0  DefTransTimeout = 0
  MaxTransTimeout = 0  MinTransTimeout = 0  MaxComIDTime = 0

Host Properties:
  MaxComPacketSize = 2048  MaxPacketSize = 2028
  MaxIndTokenSize = 1992  MaxPackets = 1  MaxSubpackets = 1
  MaxMethods = 1

PS U:\Users\r0m30\Documents\Visual Studio 2015\Projects> msed --initialsetup testing \\.\PhysicalDrive1
- 14:16:50.000 INFO: takeownership complete
- 14:16:52.090 INFO: Locking SP Activate Complete
- 14:16:53.777 INFO: LockingRange0 disabled
- 14:16:53.136 INFO: LockingRange0 set to RW
- 14:16:54.572 INFO: MBRDone set on
- 14:16:54.978 INFO: MBREnable set on
- 14:16:54.978 INFO: Initial setup of TPer complete on \\.\PhysicalDrive1
PS U:\Users\r0m30\Documents\Visual Studio 2015\Projects> msed --query \\.\PhysicalDrive1

\\.\PhysicalDrive1 ATA ST500LT025-1DH142                        0001SDM7             W3P34NH9
TPer function (0x0001)
    ACKNAK = N, ASYNC = N. BufferManagement = N, comIDManagement  = N, Streaming = Y, SYNC = Y
Locking function (0x0002)
    Locked = N, LockingEnabled = Y, LockingSupported = Y, MBRDone = Y, MBREnabled = Y, MediaEncrypt = Y
Geometry function (0x0003)
    Align = Y, Alignment Granularity = 8 (4096), Logical Block size = 512, Lowest Aligned LBA = 0
SingleUser function (0x0201)
    ALL = N, ANY = N, Policy = Y, Locking Objects = 16
DataStore function (0x0202)
    Max Tables = 16, Max Size Tables = 52428800, Table size alignment = 4096
OPAL 2.0 function (0x0203)
    Base comID = 0x07fe, Initial PIN = 0x0 , Reverted PIN = 0x0 , comIDs = 2
    Locking Admins = 4, Locking Users = 16, Range Crossing = N

TPer Properties:
  MaxMethods = 1  MaxSubpackets = 1
  MaxPacketSize = 17388  MaxPackets = 1  MaxComPacketSize = 17408
  MaxResponseComPacketSize = 17408  MaxSessions = 1  MaxIndTokenSize = 17352
  MaxAuthentications = 24  MaxTransactionLimit = 1  DefSessionTimeout = 0
  MaxSessionTimeout = 0  MinSessionTimeout = 0  DefTransTimeout = 0
  MaxTransTimeout = 0  MinTransTimeout = 0  MaxComIDTime = 0

Host Properties:
  MaxComPacketSize = 2048  MaxPacketSize = 2028
  MaxIndTokenSize = 1992  MaxPackets = 1  MaxSubpackets = 1
  MaxMethods = 1

PS U:\Users\r0m30\Documents\Visual Studio 2015\Projects> dir e:


    Directory: e:\


Mode                LastWriteTime     Length Name
----                -------------     ------ ----
-a---         8/23/2015   2:15 PM          0 THis should still be here after im done.txt


PS U:\Users\r0m30\Documents\Visual Studio 2015\Projects> msed --rawCmd 3 0000000900010001 testing 0000000000000001 0000000600000011 f0f2840006000001f3f1  \\.\PhysicalDrive1
- 14:17:40.000 INFO: Command:
0000 00000000 00000000 00000000 00000000  ................
0010 00000048 00000000 00000000 00000000  ...H............
0020 00000000 00000000 00000030 00000000  ...........0....
0030 00000000 00000023 f8a80000 00000000  .......#........
0040 0001a800 00000600 000011f0 f2840006  ................
0050 000001f3 f1f9f000 0000f100           ............
- 14:17:43.184 INFO: Response:
0000 00000000 07fe0000 00000000 00000000  ................
0010 0000002c fffffc8d 00000069 00000000  ...,.......i....
0020 00000000 00000000 00000014 00000000  ................
0030 00000000 00000008 f0f1f9f0 000000f1  ................
- 14:17:43.231 ERR : One or more header fields have 0 length
- 14:17:43.231 ERR : EndSession Failed
PS U:\Users\r0m30\Documents\Visual Studio 2015\Projects> msed --query \\.\PhysicalDrive1

\\.\PhysicalDrive1 ATA ST500LT025-1DH142                        0001SDM7             W3P34NH9
TPer function (0x0001)
    ACKNAK = N, ASYNC = N. BufferManagement = N, comIDManagement  = N, Streaming = Y, SYNC = Y
Locking function (0x0002)
    Locked = N, LockingEnabled = N, LockingSupported = Y, MBRDone = N, MBREnabled = N, MediaEncrypt = Y
Geometry function (0x0003)
    Align = Y, Alignment Granularity = 8 (4096), Logical Block size = 512, Lowest Aligned LBA = 0
SingleUser function (0x0201)
    ALL = N, ANY = N, Policy = Y, Locking Objects = 16
DataStore function (0x0202)
    Max Tables = 16, Max Size Tables = 52428800, Table size alignment = 4096
OPAL 2.0 function (0x0203)
    Base comID = 0x07fe, Initial PIN = 0x0 , Reverted PIN = 0x0 , comIDs = 2
    Locking Admins = 4, Locking Users = 16, Range Crossing = N

TPer Properties:
  MaxMethods = 1  MaxSubpackets = 1
  MaxPacketSize = 17388  MaxPackets = 1  MaxComPacketSize = 17408
  MaxResponseComPacketSize = 17408  MaxSessions = 1  MaxIndTokenSize = 17352
  MaxAuthentications = 24  MaxTransactionLimit = 1  DefSessionTimeout = 0
  MaxSessionTimeout = 0  MinSessionTimeout = 0  DefTransTimeout = 0
  MaxTransTimeout = 0  MinTransTimeout = 0  MaxComIDTime = 0

Host Properties:
  MaxComPacketSize = 2048  MaxPacketSize = 2028
  MaxIndTokenSize = 1992  MaxPackets = 1  MaxSubpackets = 1
  MaxMethods = 1

PS U:\Users\r0m30\Documents\Visual Studio 2015\Projects> dir e:


    Directory: e:\


Mode                LastWriteTime     Length Name
----                -------------     ------ ----
-a---         8/23/2015   2:15 PM          0 THis should still be here after im done.txt


PS U:\Users\r0m30\Documents\Visual Studio 2015\Projects> msed --reverttper testing \\.\PhysicalDrive1
- 14:18:15.000 INFO: revertTper completed successfully
PS U:\Users\r0m30\Documents\Visual Studio 2015\Projects> dir e:


    Directory: e:\


Mode                LastWriteTime     Length Name
----                -------------     ------ ----
-a---         8/23/2015   2:15 PM          0 THis should still be here after im done.txt


PS U:\Users\r0m30\Documents\Visual Studio 2015\Projects> msed --query \\.\PhysicalDrive1

\\.\PhysicalDrive1 ATA ST500LT025-1DH142                        0001SDM7             W3P34NH9
TPer function (0x0001)
    ACKNAK = N, ASYNC = N. BufferManagement = N, comIDManagement  = N, Streaming = Y, SYNC = Y
Locking function (0x0002)
    Locked = N, LockingEnabled = N, LockingSupported = Y, MBRDone = N, MBREnabled = N, MediaEncrypt = Y
Geometry function (0x0003)
    Align = Y, Alignment Granularity = 8 (4096), Logical Block size = 512, Lowest Aligned LBA = 0
SingleUser function (0x0201)
    ALL = N, ANY = N, Policy = Y, Locking Objects = 16
DataStore function (0x0202)
    Max Tables = 16, Max Size Tables = 52428800, Table size alignment = 4096
OPAL 2.0 function (0x0203)
    Base comID = 0x07fe, Initial PIN = 0x0 , Reverted PIN = 0x0 , comIDs = 2
    Locking Admins = 4, Locking Users = 16, Range Crossing = N

TPer Properties:
  MaxMethods = 1  MaxSubpackets = 1
  MaxPacketSize = 17388  MaxPackets = 1  MaxComPacketSize = 17408
  MaxResponseComPacketSize = 17408  MaxSessions = 1  MaxIndTokenSize = 17352
  MaxAuthentications = 24  MaxTransactionLimit = 1  DefSessionTimeout = 0
  MaxSessionTimeout = 0  MinSessionTimeout = 0  DefTransTimeout = 0
  MaxTransTimeout = 0  MinTransTimeout = 0  MaxComIDTime = 0

Host Properties:
  MaxComPacketSize = 2048  MaxPacketSize = 2028
  MaxIndTokenSize = 1992  MaxPackets = 1  MaxSubpackets = 1
  MaxMethods = 1

PS U:\Users\r0m30\Documents\Visual Studio 2015\Projects>

**Comment by Cysioland** [comment]
Why do you revertTper after that?

**Comment by r0m30** [comment]
The revertnoerase resets the locking sp, the revertTper resets the admin sp
(and the locking sp if it is active).  If you don't do the revertTper the
sid password is not reset to the default.

________
Mike

**Comment by Cysioland** [comment]
@r0m30 Then why in the help it says, that revertTper erases data? I don't want to erase my data, I just want to disable the encryption. If I wanted to erase the data, I'd go straight with PSID.

**Comment by r0m30** [comment]
In the "normal" use case the revertTper will delete (crypto-erase) your data because the locking SP will be active. The revertTper will deactivate all active SP's and reset the drive password to the default (MSID) password.  If the locking SP is deactivated it changes the media encryption key UNLESS it is deactivated with the keepglobalrange parameter.  To prevent data loss when taking the drive out of OPAL mode we must deactivate the locking SP first with the keepglobalrange parameter so the media encryption key is not changed.  Then since the locking SP is already inactive the revertTper command only resets the admin SP to defaults and your data is not erased.

**Comment by Cysioland** [comment]
@r0m30 Well, I'll image it anyway, so I don't really care. And removing the password is very desired by me (will probably forget it in few months when you will finally fix #23 and/or #16).

**Comment by Cysioland** [comment]
@r0m30 Unfortunately, didn't work (no data loss though :grinning:)
```
$ sudo ./msed --rawCmd 3 0000000900010001 mypassword 0000000000000001 0000000600000011 f0f2840006000001f3f1 /dev/sda
- 20:46:34.731 INFO: Command:
0000 00000000 00000000 00000000 00000000  ................ 
0010 00000048 00000000 00000000 00000000  ...H............ 
0020 00000000 00000000 00000030 00000000  ...........0.... 
0030 00000000 00000023 f8a80000 00000000  .......#........ 
0040 0001a800 00000600 000011f0 f2840006  ................ 
0050 000001f3 f1f9f000 0000f100           ............
- 20:46:34.758 ERR : method status code INVALID_PARAMETER
```

**Comment by r0m30** [comment]
Invalid parameter is usually the error you get when the locking sp is already inactive.  What does a query of the drive show?

**Comment by Cysioland** [comment]
@r0m30 I'll just paste the relevant part:
```
Locked = N, LockingEnabled = Y, LockingSupported = Y, MBRDone = N, MBREnabled = N, MediaEncrypt = Y
```

**Comment by r0m30** [comment]
That's strange can you try:
sudo ./msed --rawCmd 3 0000000900010001 mypassword 0000000000000001 0000000600000011 f0f28306000001f3f1 /dev/sda

That should give you FAIL again.

**Comment by Cysioland** [comment]
You're right

```
- 22:41:34.287 INFO: Command:
0000 00000000 00000000 00000000 00000000  ................ 
0010 00000048 00000000 00000000 00000000  ...H............ 
0020 00000000 00000000 00000030 00000000  ...........0.... 
0030 00000000 00000022 f8a80000 00000000  ......."........ 
0040 0001a800 00000600 000011f0 f2830600  ................ 
0050 0001f3f1 f9f00000 00f10000           ............
- 22:41:34.314 ERR : method status code FAIL
```

**Comment by r0m30** [comment]
At this point it seems pretty certain it is a firmware bug, you can try contacting Crucial customer support.
The only option I know of would be to image the drive, do a PSID revert and restore your data.

**Comment by Cysioland** [comment]
@r0m30 It's not an urgent matter, so I'll wait with PSID revert until I'll reinstall my OS.

Will try to contact support, but they may not be helpful.

**Comment by Cysioland** [comment]
@r0m30 Also, there is a new firmware for my drive, I may try to install it.

**Comment by Cysioland** [comment]
@r0m30 Tried on new firmware, still fails.

And I'd like to avoid PSID revert, as I feel my case will help to improve the msed

**Comment by r0m30** [comment]
@Cysioland  Can you try the new PBA?  (biospba_test.img)?  revertnoerase now works on my MX200 and the only thing that I know I changed is using that PBA.  I'm thinking that the old PBA could have left the drive in some undefined state, but am really not sure why revertnoerase now works on my MX200.

**Comment by Cysioland** [comment]
So I need to enable locking, then flash the PBA, then reboot, unlock the
disk with it, and then revert?

**Comment by r0m30** [comment]
You'll also need to --setMBREnable on and power off to lock the disk.

**Comment by Cysioland** [comment]
So basically encrypt the disk according to tutorial I encrypted it with
before.

**Comment by r0m30** [comment]
Sort of, but you can't use initialsetup because the locking sp is already active so you need to start at the step after that.

**Comment by Cysioland** [comment]
Okay, I'm imaging the disk in case of needing to nuke it, and then I'll
proceed.

**Comment by Cysioland** [comment]
@r0m30 The same happened. New PBA boots just fine, but it can't unlock my device ("Found device" forever), so I had to boot the rescue image, disable locking and MBR, and then I was able to access my data.

**Comment by r0m30** [comment]
Did you try the --revertnoerase to remove OPAL before you disabled the locking?

**Comment by Cysioland** [comment]
@r0m30 Tried with and without lock, still fails.

**Comment by Cysioland** [comment]
@r0m30 I also forwarded this issue's URL to Crucial support, but I doubt they will do anything about it.

**Comment by r0m30** [comment]
@Cysioland  This doesn't appear to be a Crucial bug, as I said earlier in the thread revertnoerase now works on the MX200 I bought and it always worked on the M5xx series.  Did you ever have an ATA password on the Drive?  What does a query of the drive look like?

PS.  The bug with the PBA load has been identified and should be fixed soon.

**Comment by Cysioland** [comment]
I had ATA password, and I removed it. My drive query is somewhere here,
when I'll get home, I'll give you an up-to-date one.

**Comment by Cysioland** [comment]
@r0m30 Here is my query: https://gist.github.com/Cysioland/c3a8c089d17e74dd5680

**Comment by r0m30** [comment]
I purchased a MX200 to test this and mine is NOT failing.....  This is really strange and I'm not sure what to look for to solve this.

If you want to try and load the LinuxPBA I have posted a testfix for issue #23 on that thread and you should be able to load the PBA now to see if that works.

**Comment by britcan** [comment]
Hello. I thought I would add my experience with the MX200 and ask a question. I started using msed earlier in the year. I bought an MX200 first before realizing it was a "problem drive" and ran into the expected problems (I didn't see r0m30's post on it until after purchasing the drive). I then bought a Samsung 850 EVO and have been using it successfully ever since.

Yesterday evening I decided to try the MX200 using the biospba_test.img pre-boot authentication image. I used the latest 0.23beta version of msed in Windows 7 and on a bootable rescue USB stick to set the drive up and manage it. 

I set the drive up from Windows 7. The drive successfully locks and the shadow MBR activates properly. I rebooted a couple of times and everything works as expected. 

Using either msed in Windows 7 or the rescue USB, I can unlock the drive with
msed --disableLockingRange 0 <password> /dev/sda

but I cannot deactivate the shadow MBR with 

msed --setMBREnable off <password> /dev/sda

When issued, the "setMBREnable off" command provides what appears to be normal feedback but it is ineffectual. When I query the drive, the output indeed shows that it is unlocked but that the MBREnabled is still active:

Locked = N, LockingEnabled = Y, LockingSupported = Y, MBRDone = Y, MBREnabled = Y 

I am running this on a Samsung Series 9 laptop circa 2012 dual booting Windows 7 Professional and KUbuntu 14.04. The bios can probably be considered legacy pre-Windows 8 although UEFI is available but turned off. 

I am not a developer and have not tried the LinuxPBA utility. I hope this information is useful. Does anyone have any insight into getting the --setMBREnable to off command to work with the MX200?

**Comment by r0m30** [comment]
Hi,

The Drive Trust Alliance version of the software is newer and has fixed the bugs in msed that caused most of the issues experienced with the Crucial line of SSDs.  I have a MX200 as my win7 system drive and am able to issue the setMBREnable off without issue (even with the 0.23 msed version).

See Drive-Trust-Alliance/sedutil for the latest source and executables.

If you still have issues with the newer software please run a trace and open an issue on the sedutil repo.

Unfortunately I am unable to recreate the FAIL issue.

**Comment by Cysioland** [comment]
I'm glad to say, that
* Routine encryption/decryption is going smoothly, with LinuxPBA being flashable onto my MX100, and it unlocking my drive properly
* `--revertnoerase` paired with `--reverttper` executed successfully, which effectively allows me to resetup encryption with a stronger passphrase

All thanks to @r0m30's excellent work at Drive-Trust-Alliance/sedutil
