### ISSUE TITLE
PBA does not detect drive at boot up

### ISSUE THREAD

**Issue by fswane** [r0m30/msed#32]
Good morning

I used this great-looking software (thanks a lot!) and followed the steps posted by cpbotha (http://vxlabs.com/tag/msed/) to enable OPAL on my Samsung SSD 850 PRO 256GB (firmware EXM02B6Q).  All went well -- until I tried to reboot.  Entering my password did not work at all!  Not a great way to start the weekend as I thought all my data are lost.

I am using MSED version 0.23beta (Release_x86_64) on Ubuntu 14.04.  My laptop hosting the SSD is a Dell Latitude E6330.

Anyway, after reading the documentation again, I created a boot USB with image biospba-0.23beta.img and realised that my drive is not detected during boot time.  After the password is entered it immediately says "About to Chainload hd0,0 Booting...".  No devices are found.  See the photo from this screen:

![pba](https://cloud.githubusercontent.com/assets/13535470/9032562/33bde1a6-39c0-11e5-92a9-6890b83eb981.jpg)

Fortunately I was able to unlock the drive and retain my data by doing:
msed --disableLockingRange 0 <password> /dev/sda
msed --setMBREnable off <password> /dev/sda

Additional information for debugging -- When scanning I get an error log "ERR : Identify failed Invalid argument" as shown below.  Perhaps this is linked to why the PBA does not detect the drive?
```
-------------------------------------
sudo ./msed -vvvvv --scan
- 06:21:34.376 DBG : Log level set to DBG4
- 06:21:34.376 DBG : msed version : 0.23beta
- 06:21:34.376 DBG : Performing diskScan()
- 06:21:34.376 DBG1: Creating diskList

Scanning for Opal compliant disks
- 06:21:34.376 DBG1: Creating  MsedResponse()
- 06:21:34.376 DBG1: Creating  MsedResponse()
- 06:21:34.376 DBG1: Creating MsedDevOS::MsedDev() /dev/sda
- 06:21:34.376 DBG4: Entering MsedDevOS::identify()
- 06:21:34.376 DBG1: Entering MsedDev::discovery0()
- 06:21:34.376 DBG1: Entering MsedDevOS::sendCmd
- 06:21:34.378 DBG3: Dumping D0Response
- 06:21:34.378 DBG1: Entering hexDump
0000 000000a4 00000001 00000000 00000000  ................
0010 00000000 00000000 00000000 00000000  ................
0020 00000000 00000000 00000000 00000000  ................
0030 0001100c 11000000 00000000 00000000  ................
0040 0002100c 1f000000 00000000 00000000  ................
0050 0003101c 00000000 00000000 00000200  ................
0060 00000000 00000001 00000000 00000000  ................
0070 02001010 10040001 00000000 00000000  ................
0080 00000000 0202100c 00000009 00a00000  ................
0090 00000001 02031010 10040001 00000400  ................
00a0 09000000                             ....
- 06:21:34.379 DBG1: Entering MsedDev::isPresent() 1
- 06:21:34.379 DBG1: Entering MsedDev::isAnySSC 1
- 06:21:34.379 DBG1: Entering MsedDev::isEprise 0
- 06:21:34.379 DBG1: Entering MsedDev::isOpal2 1
- 06:21:34.379 DBG1: Entering MsedDev::isOpal1() 1
/dev/sda 12  Samsung SSD 850 PRO 256GB                EXM02B6Q
- 06:21:34.379 DBG1: Destroying MsedResponse
- 06:21:34.379 DBG1: Destroying MsedResponse
- 06:21:34.379 DBG1: Creating  MsedResponse()
- 06:21:34.379 DBG1: Creating  MsedResponse()
- 06:21:34.379 DBG1: Creating MsedDevOS::MsedDev() /dev/sdb
- 06:21:34.379 DBG4: Entering MsedDevOS::identify()
- 06:21:34.379 ERR : Identify failed Invalid argument
- 06:21:34.379 DBG1: Entering MsedDev::isPresent() 1
- 06:21:34.379 DBG1: Entering MsedDev::isAnySSC 0
-------------------------------------
```

Query log:
```
lubuntu@lubuntu:/cdrom/msed/msed/Release_x86_64$ sudo ./msed --query /dev/sda

/dev/sda ATA Samsung SSD 850 PRO 256GB                EXM02B6Q S251NWAG207691H    
TPer function (0x0001)
    ACKNAK = N, ASYNC = N. BufferManagement = N, comIDManagement  = N, Streaming = Y, SYNC = Y
Locking function (0x0002)
    Locked = Y, LockingEnabled = Y, LockingSupported = Y, MBRDone = N, MBREnabled = Y, MediaEncrypt = Y
Geometry function (0x0003)
    Align = N, Alignment Granularity = 1 (512), Logical Block size = 512, Lowest Aligned LBA = 0
Opal V1.0 function (0x0200)
Base comID = 0x1004, comIDs = 1
DataStore function (0x0202)
    Max Tables = 9, Max Size Tables = 10485760, Table size alignment = 1
OPAL 2.0 function (0x0203)
    Base comID = 0x1004, Initial PIN = 0x0, Reverted PIN = 0x0, comIDs = 1
    Locking Admins = 4, Locking Users = 9, Range Crossing = N

TPer Properties:
  MaxComPacketSize = 66048  MaxResponseComPacketSize = 66048
  MaxPacketSize = 66028  MaxIndTokenSize = 65992  MaxPackets = 1
  MaxSubpackets = 1  MaxMethods = 1  MaxAuthentications = 5
  MaxSessions = 1  MaxTransactionLimit = 1  DefSessionTimeout = 0

Host Properties:
  MaxComPacketSize = 2048  MaxResponseComPacketSize = 2048
  MaxPacketSize = 2028  MaxIndTokenSize = 1992  MaxPackets = 1
  MaxSubpackets = 1  MaxMethods = 1
---------------------------------------------------------------------
```
Any assistance would be appreciated very much.

Regards
Francois

**Comment by r0m30** [comment]
I would recommend trying  the LinuxPBARelease instead of the BIOSPBA, the
biosPBA writes directly to the HBA to communicate with the disk,
 has limited error recovery and seems to fail miserably on laptops and
drives with aggressive power management.

Does your machine have two drives?  the identify error is on /dev/sdb.  The
scan logic just increments the drive designation and sees if there is
a drive there so that is normal behavior on a single drive system.

----------
Mike

**Comment by fswane** [comment]
Hi Mike

Thanks for the suggestion.  I am very happy to report that it worked (by using LinuxPBARelease instead of the BIOSPBA).  I simply reloaded the LinuxPBARelease using 

```sudo./msed --loadPBAimage mylongpassword LINUXPBARelease-0.23beta.img  /dev/sda```

After enabling locking again and rebooting it worked as advertised.  Great.

(Re your question about whether I have two drives: The second one (/dev/sdb) was the USB I had to boot from to recover /dev/sda.  So no, only one drive normally.)

Many thanks for the help and this great tool.

Cheers
Francois

**Comment by 0maboy** [comment]
I'd like to enable TCG Opal on my Samsung 850 EVO (in my HP DV9000 Laptop with Xubuntu 15.10),too.

First I tried this with biospba of MSED version 0.23beta (Release_x86_64) by following the steps posted by cpbotha (http://vxlabs.com/tag/msed/), but it didn't work. On startup Syslinux reported a "Boot Error" w/o any further information. With Rescue-0.23beta.img and msed --scan I was able to determine that there was the following Error: "ERR : Identify failed Invalid argument".

That's why I found this ticket, which is similar to my issue.

Then I unlocked the drive by:
msed --disableLockingRange 0 /dev/sda
msed --setMBREnable off /dev/sda

Afterwards I downloaded LINUXPBARelease-0.23beta.img.gz and tried the solution mentioned above:

sudo./msed --loadPBAimage mylongpassword LINUXPBARelease-0.23beta.img /dev/sda

And finally I re-enabled Opal.

But again Opal is not working correctly. Now it asks me for the pw and the pw seems to be accepted, but about 5 sec. after entering the pw, my laptop restarts w/o any message.

Now I had to disable Opal again, but I'd really like to use it, since the drive is encrypted anyway an in my opinion FDE without password is the worst thing I can think of.

**Comment by 0maboy** [comment]
Now I've tried it with SEDutil 1.10, too.

My commands to re-enable OPAL have been:

sudo ./sedutil-cli --loadPBAimage <PWD> LINUXPBARelease-1.10.img /dev/sda

sudo ./sedutil-cli --setMBREnable on <PWD> /dev/sda
sudo ./sedutil-cli --enableLockingRange 0 <PWD> /dev/sda

...it's still not working. I had to disable it again, but I have to admit that I didn't follow this site:

https://github.com/Drive-Trust-Alliance/sedutil/wiki/Encrypting-your-drive

...where the following steps are suggested:

sedutil-cli -–enableLockingRange 0 <password> <drive>    
sedutil-cli –-setMBRDone on <password> <drive>  
sedutil-cli –-setMBREnable on <password> <drive>

Anyway, even after loading LINUXPBARelease-1.10.img the result of sedutil --scan is still the same:

ERR : Identify failed Invalid argument

Thus, I checked:

cat /sys/module/libata/parameters/allow_tpm

...which delivered: 1

...and at this point I'm helpless.

Can I redo the initial setup with the latest version somehow? Maybe something went wrong with the first initial setup.

**Comment by r0m30** [comment]
I'm having trouble following what you are doing.  You list the setup commands but then you say a  scan gives you an error of ERR : Identify failed Invalid argument.  If you are getting that error them you should be getting errors on the other commands as well.

What is the output from a query command?  Is your system installed in UEFI mode?  

There is something that's not falling in place for me from you description of the problem.

**Comment by 0maboy** [comment]
In fact msed --scan (and sedutil-cli --scan) do not give me the "ERR : Identify failed Invalid argument" under Xubuntu any more. This obviously happened because I've entered "msed --scan" directly after disabling opal using the rescue image.

I was able to reproduce that by:

1. Re-activating opal with the actually suggested steps under Xubuntu:

sedutil-cli -–enableLockingRange 0 PWD DRIVE
sedutil-cli –-setMBRDone on PWD DRIVE
sedutil-cli –-setMBREnable on PWD DRIVE

2. Rebooting with no success (PC crashes about 5 sec. after entering correct PWD; with wrong PWD it tells me, that it's not able to boot and it reboots directly)

3. Using the Rescue-0.23beta.img to unlock and scan:

msed --disableLockingRange 0 PWD /dev/sda
msed --setMBREnable off PWD /dev/sda
msed --scan

=> in this case I get  "ERR : Identify failed Invalid argument" because its seems to necessary to reboot before checking "msed --scan"

**Comment by 0maboy** [comment]
I forgot:

No UEFI, my HP DV9700-Series Notebook PC is far too old for that. It has a traditional BIOS.

And here's the result of --query

rennie@Hopp:~/sedutil/Release_x86_64/GNU-Linux-x86$ sudo ./sedutil-cli --query /dev/sda
[sudo] Passwort für rennie: 

/dev/sda ATA Samsung SSD 850 EVO 250GB                EMT02B6Q S21PNXAG346470K     
TPer function (0x0001)
    ACKNAK = N, ASYNC = N. BufferManagement = N, comIDManagement  = N, Streaming = Y, SYNC = Y
Locking function (0x0002)
    Locked = N, LockingEnabled = Y, LockingSupported = Y, MBRDone = N, MBREnabled = N, MediaEncrypt = Y
Geometry function (0x0003)
    Align = N, Alignment Granularity = 1 (512), Logical Block size = 512, Lowest Aligned LBA = 0
Opal V1.0 function (0x0200)
Base comID = 0x1004, comIDs = 1
SingleUser function (0x0201)
    ALL = N, ANY = N, Policy = Y, Locking Objects = 9
DataStore function (0x0202)
    Max Tables = 9, Max Size Tables = 10485760, Table size alignment = 1
OPAL 2.0 function (0x0203)
    Base comID = 0x1004, Initial PIN = 0x0, Reverted PIN = 0x0, comIDs = 1
    Locking Admins = 4, Locking Users = 9, Range Crossing = N

TPer Properties: 
  MaxComPacketSize = 66048  MaxResponseComPacketSize = 66048
  MaxPacketSize = 66028  MaxIndTokenSize = 65992  MaxPackets = 1
  MaxSubpackets = 1  MaxMethods = 1  MaxAuthentications = 5
  MaxSessions = 1  MaxTransactionLimit = 1  DefSessionTimeout = 0

Host Properties: 
  MaxComPacketSize = 2048  MaxResponseComPacketSize = 2048
  MaxPacketSize = 2028  MaxIndTokenSize = 1992  MaxPackets = 1
  MaxSubpackets = 1  MaxMethods = 1
rennie@Hopp:~/sedutil/Release_x86_64/GNU-Linux-x86$

**Comment by r0m30** [comment]
When are you getting the ERR identify failed?  Are you running it with the trace option?  If so the scan loops through the sd* devices and will get that error when it reached the end of you sd* /dev entries.  That is how it knows to stop the scan.  Can you post a trace (-vvvvv) option?

I can't figure out why the rescue image would work but not the linux based PBA they are both the same kernel etc so if it works in one it should work in the other.

**Comment by 0maboy** [comment]
My fault! I get ERR identify failed, when a second HDD is installed/mounted. I didn't know that these errors concerned only my other drives, which weren't always present/mounted. I thought that errors of msed --scan would only be displayed for drives that use FDE. 

Nevertheless, my fault doesn't change the situation dramatically.

When opal is active, my system doesn't boot, but the notebook restarts after entering a PW (wrong or right doesn't matter).

The only thing that I can contribute at this point is a photo of my screen, that I took when I entered a random wrong PW, which caused the notebook to restart:

![p1230607_jpg7](https://cloud.githubusercontent.com/assets/16814672/12585906/62651dd0-c44e-11e5-9fde-84be09b6ba17.JPG)

As you can see, I get some informations before the crash (automatic restart) when I enter a random PW (while the laptop crashes/reboots w/o any info when the correct PW is entered).
