### ISSUE TITLE
PBA will not complete the boot if drive is not locked.

### ISSUE THREAD

**Issue by lellis1936** [r0m30/msed#42]
Don't know if technically possible, but my experience was the if the PBA was installed and enabled, but the drive was not locked, the boot would simply re-prompt for the password repeatedly.   Would be nice if it just finished the Windows boot; otherwise you need  rescue media to get out of this state.

**Comment by r0m30** [comment]
Which PBA are you using?  It sounds like I may need to add a check of the MBREnable setting even if the drive in not locked.

**Comment by lellis1936** [comment]
bios-pba-0.23beta.

**Comment by lellis1936** [comment]
I may not have described this system thoroughly.   What happened is I installed and enabled the PBA, but failed  to issue this command:

msed --enableLockingRange 0 <password> <drive>

**Comment by r0m30** [comment]
@lellis1936 No, you described the issue well enough for me to find the bug.  I only call the unlock/unshadow logic if the drive is locked so what you describe is a bug as the drive can be shadowed and not locked.  I hope to have this fixed in the next release.  

It took me a while to figure out why it was working on my setup. My drive is always locked because I have a locking range with only writelocking enabled on LBA's 0-2047 to protect the MBR and partition table from being altered.

BTW the next release will be via the Drive Trust Alliance, so look for the fix in Drive-Trust-Alliance/sedutil  I'll close this when the fix is available.

Thanks for the report.

**Comment by r0m30** [comment]
This issue is fixed in the latest release of sedutil
