### ISSUE TITLE
Not an issue, a question !

### ISSUE THREAD

**Issue by Xqua** [r0m30/msed#5]
Hi,

I have Ubuntu 14.04, and an SED drive (built in a laptop so the motherboard has suport for it)
On windows, I can suspend my computer and reboot as the BIOS either stocks the key, or does whatever magic to the disk but keeps it unlocked. 
But on Linux, if I suspend, the power to the disk is cut ! Thus when I unsuspend the computer, it boots up on the ram but crashes as there is no IO on the harddrive (its locked) ! 
I am looking for informations on what should I modify (probably in the kernel ? or config ? or BIOS ?) in order to avoid that !
You seem like the person to ask and I could not find your email ! 

Thanks for your time !

**Comment by r0m30** [comment]
Windows with eDrive?

It sounds like you have the drive under eDrive control and if that's the
case Windows won't let you do anything with the drive when you're not
running windows.

----------
Mike

**Comment by Xqua** [comment]
Hi, 

Isn't e-drive for Windows 8 ? Because I have an OEM windows 7. 

Moreover, everything BUT suspend works... Well if I hdparm -I my disk, I don't see any "Encryption" menu ... It may well be that there is some windowsy thingy here that I am missing... but windows does no magic ! it probably calls for something on suspend no ?

**Comment by Xqua** [comment]
Maybe that would be usefull ?

sudo hdparm -I /dev/sda
[sudo] password for xqua: 

/dev/sda:

ATA device, with non-removable media
	Model Number:       ST500LT015-9WU142                       
	Serial Number:      W0VBZQQ7
	Firmware Revision:  0001SDM7
	Transport:          Serial, ATA8-AST, SATA 1.0a, SATA II Extensions, SATA Rev 2.5, SATA Rev 2.6
Standards:
	Used: unknown (minor revision code 0x0029) 
	Supported: 8 7 6 5 
	Likely used: 8
Configuration:
	Logical		max	current
	cylinders	16383	16383
	heads		16	16
	sectors/track	63	63
	--
	CHS current addressable sectors:   16514064
	LBA    user addressable sectors:  268435455
	LBA48  user addressable sectors:  976773168
	Logical  Sector size:                   512 bytes
	Physical Sector size:                  4096 bytes
	Logical Sector-0 offset:                  0 bytes
	device size with M = 1024*1024:      476940 MBytes
	device size with M = 1000*1000:      500107 MBytes (500 GB)
	cache/buffer size  = 16384 KBytes
	Form Factor: 2.5 inch
	Nominal Media Rotation Rate: 5400
Capabilities:
	LBA, IORDY(can be disabled)
	Queue depth: 32
	Standby timer values: spec'd by Standard, no device specific minimum
	R/W multiple sector transfer: Max = 1	Current = 1
	Advanced power management level: 254
	Recommended acoustic management value: 208, current value: 0
	DMA: mdma0 mdma1 mdma2 udma0 udma1 udma2 udma3 udma4 udma5 *udma6 
	     Cycle time: min=120ns recommended=120ns
	PIO: pio0 pio1 pio2 pio3 pio4 
	     Cycle time: no flow control=120ns  IORDY flow control=120ns
Commands/features:
	Enabled	Supported:
	   *	SMART feature set
	   *	Power Management feature set
	   *	Write cache
	   *	Look-ahead
	   *	Host Protected Area feature set
	   *	WRITE_BUFFER command
	   *	READ_BUFFER command
	   *	NOP cmd
	   *	DOWNLOAD_MICROCODE
	   *	Advanced Power Management feature set
	    	Power-Up In Standby feature set
	   *	SET_FEATURES required to spinup after power up
	    	SET_MAX security extension
	   *	48-bit Address feature set
	   *	Device Configuration Overlay feature set
	   *	Mandatory FLUSH_CACHE
	   *	FLUSH_CACHE_EXT
	   *	SMART error logging
	   *	SMART self-test
	   *	General Purpose Logging feature set
	   *	WRITE_{DMA|MULTIPLE}_FUA_EXT
	   *	64-bit World wide name
	   *	IDLE_IMMEDIATE with UNLOAD
	   *	Write-Read-Verify feature set
	   *	WRITE_UNCORRECTABLE_EXT command
	   *	{READ,WRITE}_DMA_EXT_GPL commands
	   *	Segmented DOWNLOAD_MICROCODE
	   *	Gen1 signaling speed (1.5Gb/s)
	   *	Gen2 signaling speed (3.0Gb/s)
	   *	Native Command Queueing (NCQ)
	   *	Host-initiated interface power management
	   *	Phy event counters
	   *	Idle-Unload when NCQ is active
	    	Device-initiated interface power management
	   *	Software settings preservation
	   *	SMART Command Transport (SCT) feature set
	   *	SCT Write Same (AC2)
	   *	SCT Features Control (AC4)
	   *	SCT Data Tables (AC5)
	    	unknown 206[12] (vendor specific)
	   *	reserved 69[4]
	   *	reserved 69[7]
Logical Unit WWN Device Identifier: 5000c5006a036439
	NAA		: 5
	IEEE OUI	: 000c50
	Unique ID	: 06a036439
Checksum: correct

**Comment by r0m30** [comment]
Yes, eDrive is a Windows 8 feature but Windows 7 has bitlocker which is the
predecessor of eDrive, so that could still be turned on, or the OEM could
have installed winmagic or some other encryption software.

Hdparm doesn't have any OPAL SED support just ATA password support, so if
your drive is in OPAL mode hdparm won't tell you anything about that.  Have
you run a msed --query on the drive to see if it's opal and the locking SP
has been activated?

Have you tried to boot Ubuntu from a **completely**  powered off state?

Are you ever asked for a password to unlock the drive?

Is the machine BIOS or UEFI?

I'm guessing since I know very little about your system but it sounds like
you have some level of encryption turned on and windows, either through
bitlocker or other OEM software, is unlocking the drive after you resume
from sleep.

You're right it's not magic but it is poorly documented.  Windows probably
has a hook in it's resume from sleep routine that it calls when it detects
a locked drive but there is no documentation that I am aware of that tells
you how to find the pass phrase so the drive can be unlocked outside of
windows. Even if you have the passphrase you won't know how it is hashed
and salted.  Windows doesn't play well with others and probably never will.


PS received the hdparm output while I was writing this but as I said above
hdparm is unaware of OPAL.  I have a ST500LT025 and it is OPAL 2.0


----------
Mike

**Comment by Xqua** [comment]
Hi, 
Yes each cold boot I do, the disk boots up on the "mini" OS that is non encrypted. Here is what happens
Boot -> BIOS Ask MBR -> Disk anwsers HDD encryption mini  OS MBR -> computer boots mini OS -> login password check -> Disk unlocks -> Machine reboots -> BIOS ask MBR -> Disk anwsers real MBR -> Grub boots 
Then I choose the OS. 

the BIOS is UEFI.

I have noticed that it is clearly poorly documented ! it's quite crazy ! you can find very little real info online ! I can find a lot of "vague" informations but no tech doc ...

I am having an idea, what if windows on boot from RAM (suspend) detects lock state, and sends the unlock command ? 
In that case, would it be possible to configure msed to send that command on boot from suspend ?

**Comment by Xqua** [comment]
Oh just reread your statement, that's what you are saying ... then if  its OPAL there is no spec that would allow me to get that key ? What if I boot on windows and use bitlocker ? on other tools ? no way to get that key ? ...

**Comment by r0m30** [comment]
That sounds like an OEM encryption solution has been installed on your
machine.  Have a look at the installed programs in Windows and see if you
can find out who the vendor is and try contacting them about Linux support
that you can add to Ubuntu.  I wouldn't be surprised if the answer is no
but that's your best option for dual OS support.

The PBA reboots the machine?  I would have expected it to chainliad the
real OS, that's what I'm trying to develop for msed.

Yes, there is some kind of hook that the OEM software installs in windows
so that it can unlock the drive when it resumes from sleep but it would be
up to the software vendor to supply a Linux version of that software. I
know what commands it sends to the drive, they are documented in the TCG
SSC specifications but without knowing what TCG user they are using and how
they hash and salt the pass phrase there is no way to authenticate to the
drive and send the commands.

Does Ubuntu support hibernation?  If it does then your best bet would be to
set up Ubuntu to hibernate so that the PBA can unlock the drive.

Re your followup, it's not just OPAL, if an encryption solution gave up
it's keys then it wouldn't be very secure would it?



----------
Mike

**Comment by Xqua** [comment]
Ok, that makes things clear in my head regarding what's going on ! 
I will have to get my hands dirty and reboot on Windows...
I was going for suspend 'cause Hibernate does not work out of the box on this computer but yeah ! that will be the easiest solution I think ...  

I'll send an email to Dell to see wether there PBA/OEM thingy could be linuxified but I doubt it ...

Thanks a lot for those info ! If u need some testing at some point and I can be of help let me know !
