### ISSUE TITLE
UEFI support?

### ISSUE THREAD

**Issue by nmschulte** [r0m30/msed#8]
I stumbled across this project while researching my options for full disk encryption on SSDs.  Thanks for the support!

Anyway, The Opal 2.0 specification is well over my head, but I'm wondering if it's possible to support UEFI booting for the Pre-Boot Authorization image.  Is there anything in the specifications that precludes this?

**Comment by r0m30** [comment]
There is nothing in the spec that precludes UEFI support.  I have done a little research on UEFI support and it looks doable but I don't have anything to test it with, so haven't pursued it; 
UEFI doesn't support chain-loading via a master boot record in the traditional bios way so that presents a few new challenges as well.
